project_name: Asterisk Config
builds:
   - binary: asterisk-config
     env:
        - CGO_ENABLED=0
     goos:
        - linux
        - darwin
        - windows
     goarch:
        - amd64
        - arm64

archives:
   - id: asterisk-config
     format: tar.gz
     name_template: "{{ .Binary }}.{{ .Os }}.{{ .Arch }}"
     files:
      - 'defaults/*'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
       - '^docs:'
       - '^doc:'
       - '^test:'

dockers:
   - image_templates:
      - 'cycoresystems/asterisk-config:{{ .Tag }}-amd64'
      - 'cycoresystems/asterisk-config:{{ .Major }}-amd64'
      - 'cycoresystems/asterisk-config:{{ .Major }}.{{ .Minor }}-amd64'
      - 'cycoresystems/asterisk-config:latest-amd64'
      - 'ghcr.io/cycoresystems/asterisk-config:{{ .Tag }}-amd64'
      - 'ghcr.io/cycoresystems/asterisk-config:{{ .Major }}-amd64'
      - 'ghcr.io/cycoresystems/asterisk-config:{{ .Major }}.{{ .Minor }}-amd64'
      - 'ghcr.io/cycoresystems/asterisk-config:latest-amd64'
     use: buildx
     goos: linux
     goarch: amd64
     dockerfile: Dockerfile.goreleaser
     extra_files:
        - 'defaults/'
     build_flag_templates:
       - "--platform=linux/amd64"
   - image_templates:
      - 'cycoresystems/asterisk-config:{{ .Tag }}-arm64v8'
      - 'cycoresystems/asterisk-config:v{{ .Major }}-arm64v8'
      - 'cycoresystems/asterisk-config:v{{ .Major }}.{{ .Minor }}-arm64v8'
      - 'cycoresystems/asterisk-config:latest-arm64v8'
      - 'ghcr.io/cycoresystems/asterisk-config:{{ .Tag }}-arm64v8'
      - 'ghcr.io/cycoresystems/asterisk-config:v{{ .Major }}-arm64v8'
      - 'ghcr.io/cycoresystems/asterisk-config:v{{ .Major }}.{{ .Minor }}-arm64v8'
      - 'ghcr.io/cycoresystems/asterisk-config:latest-arm64v8'
     use: buildx
     goos: linux
     goarch: arm64
     dockerfile: Dockerfile.goreleaser
     extra_files:
        - 'defaults/'
     build_flag_templates:
       - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: 'cycoresystems/asterisk-config:{{ .Tag }}'
    image_templates:
      - cycoresystems/asterisk-config:{{ .Tag }}-amd64
      - cycoresystems/asterisk-config:{{ .Tag }}-arm64v8
  - name_template: 'ghcr.io/cycoresystems/asterisk-config:{{ .Tag }}'
    image_templates:
      - ghcr.io/cycoresystems/asterisk-config:{{ .Tag }}-amd64
      - ghcr.io/cycoresystems/asterisk-config:{{ .Tag }}-arm64v8
  - name_template: 'cycoresystems/asterisk-config:v{{ .Major }}'
    image_templates:
      - cycoresystems/asterisk-config:v{{ .Major }}-amd64
      - cycoresystems/asterisk-config:v{{ .Major }}-arm64v8
  - name_template: 'ghcr.io/cycoresystems/asterisk-config:v{{ .Major }}'
    image_templates:
      - ghcr.io/cycoresystems/asterisk-config:v{{ .Major }}-amd64
      - ghcr.io/cycoresystems/asterisk-config:v{{ .Major }}-arm64v8
  - name_template: 'cycoresystems/asterisk-config:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - cycoresystems/asterisk-config:v{{ .Major }}.{{ .Minor }}-amd64
      - cycoresystems/asterisk-config:v{{ .Major }}.{{ .Minor }}-arm64v8
  - name_template: 'ghcr.io/cycoresystems/asterisk-config:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - ghcr.io/cycoresystems/asterisk-config:v{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/cycoresystems/asterisk-config:v{{ .Major }}.{{ .Minor }}-arm64v8
  - name_template: 'cycoresystems/asterisk-config:latest'
    image_templates:
      - cycoresystems/asterisk-config:latest-amd64
      - cycoresystems/asterisk-config:latest-arm64v8
  - name_template: 'ghcr.io/cycoresystems/asterisk-config:latest'
    image_templates:
      - ghcr.io/cycoresystems/asterisk-config:latest-amd64
      - ghcr.io/cycoresystems/asterisk-config:latest-arm64v8
